library(tidyverse)
data(starwars)
starwars %>% select(-name)
starwars %>% select(contains("_"))
starwars %>% select(starts_with("s"))
homeworld <- starwars %>% select(name, homeworld)
human <- starwars %>% filter(species == "Human")
starwars %>% filter(species == "Human", homeworld == "Tatooine")
tarwars_nodroids <- starwars %>% filter(species != "Droid")
# ¿Cuántos registros cumplen las condiciones finales? homeworld 87, human 35, starwars 87 y starwars_nodroids 77.
starwars %>% group_by(species) %>% tally()
starwars %>% group_by(species, gender) %>% tally()
table_gender <- starwars %>% group_by(species, gender) %>% tally()
starwars %>% group_by(species) %>% summarise(mean_height = mean(height, na.rm = T),mean_mass = mean(mass,na.rm = T))
?sd()
starwars %>% group_by(species) %>% summarise(sd_height = sd(height, na.rm = T),sd_mass = sd(mass,na.rm = T))
# ¿Cómo calcularías la desviación estándar (sd) de esos parámetros? Usando sd(x, na.rm = FALSE) y sustituyendo la x por nuestro comando y cambiando las palabras "mean" por "sd".
ggplot(starwars, aes(height, mass)) + geom_point()
ggplot(starwars, aes(height, mass)) + geom_point(colour = "red")
ggplot(starwars, aes(height, mass)) + geom_point(colour = "purple", pch = 3)
ggplot(starwars, aes(height, mass)) + geom_point(colour = "red") + theme_light()
all_except_Java <- starwars %>% filter(name != "Jabba Desilijic Tiure")
ggplot(all_except_Java, aes(height, mass)) + geom_point()
toy <- read_csv("Descargas/toy.csv")
toy %>% group_by(Sex) %>% summarise(mean_Height_cm = mean(Height_cm, na.rm = T),mean_Weight_Kg = mean(Weight_Kg,na.rm = T),mean_IMC = mean(IMC, na.rm = T),mean_IAS = mean(IAS, na.rm = T),mean_Ccintura = mean(Ccintura, na.rm = T))
women <- toy %>% filter(Sex == "Women")
# Haz una tabla sólo con los pacientes femeninos ¿Cuántos registros cumplen las condiciones? 58 registros de mujeres.
womenOverweight <- women %>% filter(IMC_clas == "Overweight")
# ¿De estos cuantos tienen Sobrepeso (Overweight)? 9 registros de mujeres con sobrepeso.
ggplot(toy, aes(IMC, Weight_Kg)) + geom_point()
toy_over_obes <- toy %>% filter(IMC_clas != "Normal")
ggplot(toy_over_obes, aes(IMC, Weight_Kg)) + geom_point()
install.packages("ape")
install.packages("phangorn")
install.packages("phytools")